/**
 * Do not edit directly
 * Generated on Tue, 15 Dec 2020 13:02:39 GMT
 */

export const ColorPrimaryDefault = "#57A4D7";
export const ColorPrimaryLighter = "#338FCC";
export const ColorPrimaryDarker = "#206EA2";
export const ColorPrimaryDefaultContrast = "white";
export const ColorPrimaryLighterContrast = "white";
export const ColorPrimaryDarkerContrast = "white";
export const ColorSecondDefault = "#E6E6E6";
export const ColorSecondLighter = "#B3B3B3";
export const ColorSecondDarker = "#999999";
export const ColorSecondDefaultContrast = "#4D4D4D";
export const ColorSecondLighterContrast = "#4D4D4D";
export const ColorSecondDarkerContrast = "white";
export const ColorErrorDefault = "#FCEFEC";
export const ColorErrorLighter = "#E76E5C";
export const ColorErrorDarker = "#E04D36";
export const ColorErrorDefaultContrast = "#4D4D4D";
export const ColorErrorLighterContrast = "white";
export const ColorErrorDarkerContrast = "white";
export const ColorInfoDefault = "#EBF4FB";
export const ColorInfoLighter = "#AAD1EC";
export const ColorInfoDarker = "#57A4D7";
export const ColorInfoDefaultContrast = "#4D4D4D";
export const ColorInfoLighterContrast = "#4D4D4D";
export const ColorInfoDarkerContrast = "white";
export const ColorSuccessDefault = "#EDF8E9";
export const ColorSuccessLighter = "#B4DEA4";
export const ColorSuccessDarker = "#6FBA53";
export const ColorSuccessDefaultContrast = "#4D4D4D";
export const ColorSuccessLighterContrast = "#4D4D4D";
export const ColorSuccessDarkerContrast = "white";
export const ColorWarningDefault = "#FCF5E8";
export const ColorWarningLighter = "#F0D49B";
export const ColorWarningDarker = "#DFA739";
export const ColorWarningDefaultContrast = "#4D4D4D";
export const ColorWarningLighterContrast = "white";
export const ColorWarningDarkerContrast = "white";
export const ColorForegroundText = "#4D4D4D";
export const ColorForegroundTextLessContrast = "#999999";
export const ColorForegroundTextDisabled = "#B3B3B3";
export const ColorForegroundDivider = "#E6E6E6";
export const ColorForegroundBorder = "#B3B3B3";
export const ColorForegroundIcon = "#999999";
export const ColorBackgroundBackground = "#ffffff";
export const ColorBackgroundBackgroundPopup = "#ffffff";
export const ColorBackgroundBackgroundPopupFooter = "#F0F0F0";
export const ColorBackgroundBackgroundDisabled = "#F0F0F0";
export const ColorBackgroundOverlayHovered = "#000000";
export const ColorBackgroundOverlayActive = "#000000";
export const ColorBackgroundOverlayDisabled = "#000000";
export const ComponentButtonColorActiveShadow = "inset 0 1px 2px 0 rgba(black, 0.2)";
export const ComponentButtonColorPrimaryColor = "white";
export const ComponentButtonColorPrimaryBorderColor = "map-get($primary, 560)";
export const ComponentButtonColorPrimaryBackground = "map-get($primary, 500)";
export const ComponentButtonColorPrimaryIconColor = "white";
export const ComponentButtonColorPrimaryActiveBorderColor = "mc-color($primary, 560)"; // darken(mc-color($primary, 560), 5)
export const ComponentButtonColorPrimaryActiveBackground = "mc-color($primary, 500)"; // darken(mc-color($primary, 560), 5)
export const ComponentButtonColorSecondBorderColor = "#B3B3B3";
export const ComponentButtonColorSecondBackground = "#F0F0F0";
export const ComponentButtonColorSecondColor = "#4D4D4D";
export const ComponentButtonColorSecondIconColor = "#999999";
export const ComponentButtonColorSecondActiveBorderColor = "#B3B3B3"; // darken(mc-color($foreground, border), 5)
export const ComponentButtonColorSecondActiveBackground = "#F0F0F0"; // darken(map-get($background, background-disabled), 5
export const ComponentButtonColorErrorBorderColor = "#B3B3B3";
export const ComponentButtonColorErrorBackground = "#F0F0F0";
export const ComponentButtonColorErrorColor = "#FCEFEC";
export const ComponentButtonColorErrorIconColor = "mc-color($error, 400)";
export const ComponentButtonColorErrorActiveBorderColor = "#B3B3B3"; // darken(mc-color($foreground, border), 5)
export const ComponentButtonColorErrorActiveBackground = "#F0F0F0"; // darken(map-get($background, background-disabled), 5